# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/pwm.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/pwm.proto',
  package='pwm',
  syntax='proto3',
  serialized_pb=_b('\n\x0fproto/pwm.proto\x12\x03pwm\"E\n\x03PWM\x12\x0e\n\x06motor1\x18\x01 \x01(\x01\x12\x0e\n\x06motor2\x18\x02 \x01(\x01\x12\x0e\n\x06motor3\x18\x03 \x01(\x01\x12\x0e\n\x06motor4\x18\x04 \x01(\x01\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PWM = _descriptor.Descriptor(
  name='PWM',
  full_name='pwm.PWM',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='motor1', full_name='pwm.PWM.motor1', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='motor2', full_name='pwm.PWM.motor2', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='motor3', full_name='pwm.PWM.motor3', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='motor4', full_name='pwm.PWM.motor4', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=93,
)

DESCRIPTOR.message_types_by_name['PWM'] = _PWM

PWM = _reflection.GeneratedProtocolMessageType('PWM', (_message.Message,), dict(
  DESCRIPTOR = _PWM,
  __module__ = 'proto.pwm_pb2'
  # @@protoc_insertion_point(class_scope:pwm.PWM)
  ))
_sym_db.RegisterMessage(PWM)


# @@protoc_insertion_point(module_scope)
